ALTER TABLE pacientes
ADD COLUMN email VARCHAR(255) NOT NULL UNIQUE,
ADD COLUMN telefone VARCHAR(20) NOT NULL,
ADD COLUMN cpf CHAR(11) NOT NULL UNIQUE,

ADD COLUMN logradouro VARCHAR(100) NOT NULL,
ADD COLUMN bairro VARCHAR(60) NOT NULL,
ADD COLUMN cep CHAR(9) NOT NULL,
ADD COLUMN cidade VARCHAR(60) NOT NULL,
ADD COLUMN uf CHAR(2) NOT NULL,

ADD COLUMN numero VARCHAR(10),
ADD COLUMN complemento VARCHAR(100);